spring:

  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    web: trace
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG