spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://localhost:80/realms/myretailbusiness}
          audiences: ${AUDIENCES:billing-service}

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:discount-service}
      auto-index-creation: true
      username: ${DB_USERNAME:local}
      password: ${DB_PASSWORD:local}
      authentication-database: admin

logging:
  level:
    web: trace
